version: "3.9"
services:


  kibana:
    # image: docker.elastic.co/kibana/kibana:8.8.1
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    # command: "sleep 99999"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    restart: unless-stopped
    depends_on:
      - elasticsearch
    networks:
      - test

networks:
  test:
    name: test-network
