
FROM mcr.microsoft.com/devcontainers/python:1-3.12

# TODO sshpass,在postcreated阶段实现免密登录
RUN apt update && apt install -y vim  \
    iputils-ping netcat-openbsd \
    default-mysql-client redis-tools 

RUN mkdir /backend


# TODO 制作nodejs容器
# TODO 制作django 源码调试容器
# 1. 将的容器内源码上的笔记信息 挂载到主机上
# 2.  编辑器和代码在一个容器中，只有这样才能直接跳转编辑源码
# 3. Django包依赖所在的必须存在本地，版本管理，并且挂载容器中，镜像中不能含有这个django 包的依赖

# ARG VARIANT=22-bookworm
# FROM node:${VARIANT}

# ARG USERNAME=node
# ARG NPM_GLOBAL=/usr/local/share/npm-global

# Add NPM global to PATH.
# ENV PATH=${NPM_GLOBAL}/bin:${PATH}

# RUN \
#     # Configure global npm install location, use group to adapt to UID/GID changes
#     if ! cat /etc/group | grep -e "^npm:" > /dev/null 2>&1; then groupadd -r npm; fi \
#     && usermod -a -G npm ${USERNAME} \
#     && umask 0002 \
#     && mkdir -p ${NPM_GLOBAL} \
#     && touch /usr/local/etc/npmrc \
#     && chown ${USERNAME}:npm ${NPM_GLOBAL} /usr/local/etc/npmrc \
#     && chmod g+s ${NPM_GLOBAL} \
#     && npm config -g set prefix ${NPM_GLOBAL} \
#     && su ${USERNAME} -c "npm config -g set prefix ${NPM_GLOBAL}" \
#     # Install eslint
#     && su ${USERNAME} -c "umask 0002 && npm install -g eslint" \
#     && npm cache clean --force > /dev/null 2>&1

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install an additional version of node using nvm
# ARG EXTRA_NODE_VERSION=10
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"

# [Optional] Uncomment if you want to install more global node modules
# RUN su node -c "npm install -g <your-package-list-here>"