name: backend
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: wizard_test
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: language-kafka:9092

  kafka:
    image: apache/kafka:3.7.0
    container_name: language-kafka
    restart: unless-stopped
    ports:
      - "9092:9092" # 对外暴露Kafka服务端口
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://language-kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        #KAFKA_LOG_DIRS: "/kafka-logs"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@language-kafka:9093

        #KAFKA_NODE_ID: 1
        #KAFKA_PROCESS_ROLES: broker,controller
        #KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://language-kafka:9092
        #KAFKA_CONTROLLER_QUORUM_VOTERS: 1@language-kafka:9093
        #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        #KAFKA_LOG_DIRS: "/kafka-logs"
        #volumes:
        #- kafka-data:/var/lib/kafka/data # 持久化Kafka数据
        #- kafka-logs:/kafka-logs

        #volumes:
  #kafka-data: # 定义一个卷用于持久化Kafka数据
  #kafka-logs: # 定义一个卷用于持久化Kafka数据
