# [生产环境] 构建最终镜像

# 构建方式:
# 仅支持 [手动构建], 如果有base构建流程，需要等待base构建完成后再进行最终镜像构建

name: build [python-dev-container] and push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "image tag"
        required: true
        default: "latest"

jobs:
  deploy:
    name: build base docker image
    runs-on: ubuntu-latest

    steps:
      - name: pull code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/python-dev-container

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          platforms: linux/amd64,linux/arm64
          context: ./ops/dev-containers/.devcontainer
          file: ./ops/dev-containers/.devcontainer/Dockerfile-python-action
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/python-dev-container:${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

          # TODO 增加同步到腾讯云镜像仓库
